# Generated by Django 3.2.16 on 2022-11-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='file',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=''),
        ),
    ]
