# Generated by Django 3.2.16 on 2022-11-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='filename',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
